--------------------------------------------------------
-- Archivo creado  - miércoles-abril-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESTAURANTS
--------------------------------------------------------

  CREATE TABLE GESTIO.RESTAURANTS
   (	RES_CODI VARCHAR(3 BYTE),
	RES_NOM VARCHAR2(30 BYTE),
	RES_ADRECA VARCHAR2(100 BYTE),
	"RES_MITJANA" NUMBER(5,2), 
	"RES_LATITUD" VARCHAR2(30 BYTE), 
	"RES_LONGITUD" VARCHAR2(30 BYTE), 
	"RES_WEB" VARCHAR2(30 BYTE), 
	"RES_TELEFON" VARCHAR2(30 BYTE), 
	"RES_TRS_CODI" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."RESTAURANTS"  IS 'Clients';
--------------------------------------------------------
--  DDL for Table USUARIS
--------------------------------------------------------

  CREATE TABLE "GESTIO"."USUARIS" 
   (	"USU_CODI" VARCHAR2(3 BYTE), 
	"USU_PASSWORD" VARCHAR2(30 BYTE), 
	"USU_NOM" VARCHAR2(30 BYTE), 
	"USU_ADRECA_ELECTRONICA" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRESTAURANTS
--------------------------------------------------------

  CREATE TABLE "GESTIO"."TRESTAURANTS" 
   (	"TRS_CODI" VARCHAR2(3 BYTE), 
	"TRS_DESCRIPCIO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."TRESTAURANTS"  IS 'Tipus de clients';
--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

  CREATE TABLE "GESTIO"."TICKETS" 
   (	"TCK_CODI" VARCHAR2(3 BYTE), 
	"TCK_DATA_TICKET" DATE, 
	"TCK_TOTAL_LTICKETS" NUMBER(7,2), 
	"TCK_TOTAL_IMPOSTS" NUMBER(7,2), 
	"TCK_FAC_CODI" VARCHAR2(3 BYTE), 
	"TCK_RES_CODI" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."TICKETS"  IS 'Tickets';
--------------------------------------------------------
--  DDL for Table OPINIONS
--------------------------------------------------------

  CREATE TABLE "GESTIO"."OPINIONS" 
   (	"OPI_CODI" VARCHAR2(3 BYTE), 
	"OPI_OBSERVACIO" VARCHAR2(3000 BYTE), 
	"OPI_PUNTUACIO" NUMBER(5,2), 
	"OPI_OPINIO_REVISADA" VARCHAR2(1 BYTE), 
	"OPI_RES_CODI" VARCHAR2(3 BYTE), 
	"OPI_USU_CODI" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."OPINIONS"  IS 'Opinions';
--------------------------------------------------------
--  DDL for Table LTICKETS
--------------------------------------------------------

  CREATE TABLE "GESTIO"."LTICKETS" 
   (	"LTK_TCK_CODI" VARCHAR2(3 BYTE), 
	"LTK_CODI" VARCHAR2(3 BYTE), 
	"LTK_DESCRIPCIO" VARCHAR2(30 BYTE), 
	"LTK_UNITATS" NUMBER(5,2), 
	"LTK_TOTAL_UNITARI" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."LTICKETS"  IS 'Linies de tickets';
--------------------------------------------------------
--  DDL for Table LOG_INVOICES
--------------------------------------------------------

  CREATE TABLE "GESTIO"."LOG_INVOICES" 
   (	"LOG_ID" VARCHAR2(10 BYTE), 
	"LOG_USER" VARCHAR2(100 BYTE), 
	"LOG_DATE" DATE, 
	"LOG_TYPE" VARCHAR2(1 BYTE), 
	"LOG_DESCRIPTION" VARCHAR2(100 BYTE), 
	"LOG_INV_ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURES
--------------------------------------------------------

  CREATE TABLE "GESTIO"."FACTURES" 
   (	"FAC_CODI" VARCHAR2(3 BYTE), 
	"FAC_DATA_FACTURA" DATE, 
	"FAC_TOTAL_A_PAGAR" NUMBER(7,2), 
	"FAC_RES_CODI" VARCHAR2(3 BYTE), 
	"FAC_IMPRESA" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."FACTURES"  IS 'Factures';
--------------------------------------------------------
--  DDL for Table IMATGES
--------------------------------------------------------

  CREATE TABLE "GESTIO"."IMATGES" 
   (	"IMG_CODI" VARCHAR2(3 BYTE), 
	"IMG_PATH" VARCHAR2(30 BYTE), 
	"IMG_IMATGE" BLOB, 
	"IMG_RES_CODI" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMG_IMATGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table IMPOSTS
--------------------------------------------------------

  CREATE TABLE "GESTIO"."IMPOSTS" 
   (	"IMP_CODI" VARCHAR2(3 BYTE), 
	"IMP_DESCRIPCIO" VARCHAR2(30 BYTE), 
	"IMP_PERCENTATGE" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "GESTIO"."IMPOSTS"  IS 'Imposts';
--------------------------------------------------------
--  DDL for Table IMPXLTCK
--------------------------------------------------------

  CREATE TABLE "GESTIO"."IMPXLTCK" 
   (	"ILT_TCK_CODI" VARCHAR2(3 BYTE), 
	"ILT_LTK_CODI" VARCHAR2(3 BYTE), 
	"ILT_IMP_CODI" VARCHAR2(3 BYTE), 
	"ILT_BASE" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVOICES
--------------------------------------------------------

  CREATE TABLE "GESTIO"."INVOICES" 
   (	"INV_ID" VARCHAR2(10 BYTE), 
	"INV_DATE" DATE, 
	"INV_TYPE" VARCHAR2(1 BYTE), 
	"INV_TOTAL" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINVOICES
--------------------------------------------------------

  CREATE TABLE "GESTIO"."LINVOICES" 
   (	"LIN_INV_ID" VARCHAR2(10 BYTE), 
	"LIN_NUMBER" VARCHAR2(10 BYTE), 
	"LIN_SUBTOTAL" NUMBER(5,2), 
	"LIN_DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTS_RES_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."RESTAURANTS_RES_CODI_IDX" ON "GESTIO"."RESTAURANTS" ("RES_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTS_RES_TRS_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."RESTAURANTS_RES_TRS_CODI_IDX" ON "GESTIO"."RESTAURANTS" ("RES_TRS_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIS_USU_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."USUARIS_USU_CODI_IDX" ON "GESTIO"."USUARIS" ("USU_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRESTAURANTS_TRS_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."TRESTAURANTS_TRS_CODI_IDX" ON "GESTIO"."TRESTAURANTS" ("TRS_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKETS_TCK_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."TICKETS_TCK_CODI_IDX" ON "GESTIO"."TICKETS" ("TCK_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKETS_TCK_FAC_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."TICKETS_TCK_FAC_CODI_IDX" ON "GESTIO"."TICKETS" ("TCK_FAC_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKETS_TCK_RES_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."TICKETS_TCK_RES_CODI_IDX" ON "GESTIO"."TICKETS" ("TCK_RES_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OPINIONS_OPI_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."OPINIONS_OPI_CODI_IDX" ON "GESTIO"."OPINIONS" ("OPI_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OPINIONS_OPI_RES_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."OPINIONS_OPI_RES_CODI_IDX" ON "GESTIO"."OPINIONS" ("OPI_RES_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OPINIONS_OPI_USU_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."OPINIONS_OPI_USU_CODI_IDX" ON "GESTIO"."OPINIONS" ("OPI_USU_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LTICKETS_LTK_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."LTICKETS_LTK_CODI_IDX" ON "GESTIO"."LTICKETS" ("LTK_TCK_CODI", "LTK_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."LOG_PK" ON "GESTIO"."LOG_INVOICES" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURES_FAC_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."FACTURES_FAC_CODI_IDX" ON "GESTIO"."FACTURES" ("FAC_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURES_FAC_RES_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."FACTURES_FAC_RES_CODI_IDX" ON "GESTIO"."FACTURES" ("FAC_RES_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMATGES_IMG_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."IMATGES_IMG_CODI_IDX" ON "GESTIO"."IMATGES" ("IMG_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMATGES_IMG_RES_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."IMATGES_IMG_RES_CODI_IDX" ON "GESTIO"."IMATGES" ("IMG_RES_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPOSTS_IMP_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."IMPOSTS_IMP_CODI_IDX" ON "GESTIO"."IMPOSTS" ("IMP_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPXLTCK_TCK_IMP_CODI_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."IMPXLTCK_TCK_IMP_CODI_IDX" ON "GESTIO"."IMPXLTCK" ("ILT_TCK_CODI", "ILT_LTK_CODI", "ILT_IMP_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPXLTCK_ILT_IMP_CODI_IDX
--------------------------------------------------------

  CREATE INDEX "GESTIO"."IMPXLTCK_ILT_IMP_CODI_IDX" ON "GESTIO"."IMPXLTCK" ("ILT_IMP_CODI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."INV_PK" ON "GESTIO"."INVOICES" ("INV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTIO"."LIN_PK" ON "GESTIO"."LINVOICES" ("LIN_INV_ID", "LIN_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_RES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_RES" 
        BEFORE INSERT
        ON RESTAURANTS
        FOR EACH ROW
BEGIN
        :new.res_codi:=seq_res.NEXTVAL;

END;
/
ALTER TRIGGER "GESTIO"."TRG_RES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USU
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_USU" 
        BEFORE INSERT
        ON USUARIS
        FOR EACH ROW
BEGIN
        :new.usu_codi:=seq_usu.NEXTVAL;

END;
/
ALTER TRIGGER "GESTIO"."TRG_USU" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TRS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_TRS" 
        BEFORE INSERT
        ON TRESTAURANTS
        FOR EACH ROW
BEGIN
        :new.trs_codi:=seq_trs.NEXTVAL;

END;
/
ALTER TRIGGER "GESTIO"."TRG_TRS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TCK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_TCK" 
        BEFORE INSERT OR DELETE OR UPDATE
        ON TICKETS
        FOR EACH ROW
DECLARE
        v_fac_impresa factures.fac_impresa%TYPE;

BEGIN
        IF INSERTING THEN
                :new.tck_codi :=seq_tck.NEXTVAL;
        ELSIF (UPDATING or DELETING) AND :OLD.tck_fac_codi IS NOT NULL THEN
				SELECT fac_impresa INTO v_fac_impresa
				FROM factures
				WHERE fac_codi = :old.tck_fac_codi;
				--
				IF v_fac_impresa = 'S' THEN
						RAISE_APPLICATION_ERROR (-20001, 'Ticket facturat no modificable');
				ELSE
						UPDATE factures
						SET fac_total_a_pagar = fac_total_a_pagar
																- :OLD.tck_total_ltickets
																+ :NEW.tck_total_ltickets
                        WHERE fac_codi = :old.tck_fac_codi;
				END IF;

        END IF;
END;
/
ALTER TRIGGER "GESTIO"."TRG_TCK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_OPI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_OPI" 
        BEFORE INSERT OR UPDATE OR DELETE ON opinions
        FOR EACH ROW  

DECLARE 
	v_numopis NUMBER;
	v_mitjana NUMBER;
	v_calcul  NUMBER;
BEGIN
	IF INSERTING THEN
		:new.opi_codi := SEQ_OPI.NEXTVAL;
	END IF;
	--
	SELECT NVL(res_trs_codi,0), NVL(res_mitjana,0) INTO v_numopis, v_mitjana 
	FROM restaurants 
	WHERE res_codi = NVL(:old.opi_res_codi,:new.opi_res_codi);
	--
	BEGIN
		v_calcul := ((v_mitjana * v_numopis) + (:new.opi_puntuacio)) / (v_numopis + 1);
		--
		UPDATE restaurants
		SET res_trs_codi = res_trs_codi + 1,
		    res_mitjana = v_calcul
		WHERE res_codi = NVL(:old.opi_res_codi,:new.opi_res_codi);
	END;
END;
/
ALTER TRIGGER "GESTIO"."TRG_OPI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LTK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_LTK" 
    BEFORE INSERT 
    ON ltickets
    FOR EACH ROW
DECLARE
v_ltk_codi NUMBER;
BEGIN
    SELECT NVL(MAX(ltk_codi),0) + 1 INTO v_ltk_codi FROM ltickets WHERE ltk_tck_codi = :new.ltk_tck_codi;
END;
/
ALTER TRIGGER "GESTIO"."TRG_LTK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_LOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRIG_LOG" 
    BEFORE INSERT ON LOG_INVOICES
    FOR EACH ROW
BEGIN
    :new.log_id :=seq_log.NEXTVAL;
END;
/
ALTER TRIGGER "GESTIO"."TRIG_LOG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INV2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_INV2" 
	AFTER INSERT OR DELETE OR UPDATE
	ON invoices
	FOR EACH ROW
DECLARE
	m_log_type log_invoices.log_type%TYPE;
BEGIN
	IF INSERTING THEN
		m_log_type := 'I';
	ELSIF UPDATING THEN
		m_log_type := 'U';
	ELSIF DELETING THEN
		m_log_type := 'D';
		--
		--UPDATE invoices
		--SET inv_type = 'D'
		--WHERE inv_id = :old.inv_id;
	END IF;
	--
	INSERT INTO log_invoices
		( log_id, log_user, log_date, log_type, log_description, log_inv_id )
	VALUES
		( NULL, USER, SYSDATE, m_log_type, '.', NVL(:old.inv_id, :new.inv_id) );
END;
/
ALTER TRIGGER "GESTIO"."TRG_INV2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_INV
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRIG_INV" 
    BEFORE INSERT ON INVOICES
    FOR EACH ROW
BEGIN
    :new.inv_id :=seq_inv.NEXTVAL;
END;
/
ALTER TRIGGER "GESTIO"."TRIG_INV" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRI_LIN1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRI_LIN1" 
    BEFORE INSERT
    ON LINVOICES 
    FOR EACH ROW
DECLARE
        m_lin_number LINVOICES.LIN_NUMBER%TYPE;

BEGIN
        SELECT NVL(MAX(lin_number),0) + 1 INTO m_lin_number
        FROM linvoices
        WHERE lin_inv_id = :new.lin_inv_id;
        :new.lin_number := m_lin_number;
END;
/
ALTER TRIGGER "GESTIO"."TRI_LIN1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRI_LIN2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRI_LIN2" 
    AFTER INSERT OR UPDATE OR DELETE
    ON LINVOICES 
    FOR EACH ROW
DECLARE
        m_inv_id LINVOICES.LIN_NUMBER%TYPE;

BEGIN
       UPDATE INVOICES
        SET (SELECT NVL(MAX(inv_id),0) + 1 INTO m_inv_id
            FROM linvoices
            WHERE inv_id = :new.inv_id;)
        WHERE :new.lin_subtotal := lin_subtotal;
END
/
ALTER TRIGGER "GESTIO"."TRI_LIN2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_LIN1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRIG_LIN1" 
    BEFORE INSERT OR UPDATE ON LINVOICES
    FOR EACH ROW
DECLARE
    v_lin_number linvoices.lin_number%TYPE
BEGIN
    IF INSERTING THEN
        SELECT NVL(MAX(lin_number,0) +1 INTO v_lin_number
        FROM linvoices
        WHERE lin_inv_id = :new.lin_inv_id;
        --
        :new.lin_number :=m_lin_number;
    ELSIF UPDATING THEN
        UPDATE invoices
        SET inv_total = inv_total -
            (NVL(:OLD.lin_subtotal,0))+
            (NVL(:NEW.lin_subtotal,0))
        WHERE inv_id = NVL(:OLD.lin_inv_id, :NEW.lin_inv_id);
    ENDIF;
END;
/
ALTER TRIGGER "GESTIO"."TRIG_LIN1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LIN1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_LIN1" 
	BEFORE INSERT
	ON linvoices
	FOR EACH ROW
DECLARE
	m_lin_number linvoices.lin_number%TYPE;
BEGIN
	SELECT NVL(MAX(lin_number),0) + 1 INTO m_lin_number
	FROM linvoices
	WHERE lin_inv_id = :new.lin_inv_id;
	--
	:new.lin_number := m_lin_number;
END;
/
ALTER TRIGGER "GESTIO"."TRG_LIN1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LIN2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GESTIO"."TRG_LIN2" 
	AFTER INSERT OR UPDATE OR DELETE
	ON linvoices
	FOR EACH ROW
BEGIN
	UPDATE invoices
	SET inv_total = inv_total -
		(NVL(:OLD.lin_subtotal, 0)) +
		(NVL(:NEW.lin_subtotal, 0))
	WHERE inv_id = NVL(:OLD.lin_inv_id, :NEW.lin_inv_id);
END;
/
ALTER TRIGGER "GESTIO"."TRG_LIN2" ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTAURANTS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."RESTAURANTS" ADD CONSTRAINT "RES_RESTAURANTS_PK" PRIMARY KEY ("RES_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."RESTAURANTS" MODIFY ("RES_TRS_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."RESTAURANTS" MODIFY ("RES_ADRECA" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."RESTAURANTS" MODIFY ("RES_NOM" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."RESTAURANTS" MODIFY ("RES_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."USUARIS" ADD CONSTRAINT "USU_USUARIS_PK" PRIMARY KEY ("USU_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."USUARIS" MODIFY ("USU_ADRECA_ELECTRONICA" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."USUARIS" MODIFY ("USU_NOM" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."USUARIS" MODIFY ("USU_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRESTAURANTS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."TRESTAURANTS" ADD CONSTRAINT "TRS_TRESTAURANTS_PK" PRIMARY KEY ("TRS_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."TRESTAURANTS" MODIFY ("TRS_DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."TRESTAURANTS" MODIFY ("TRS_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."TICKETS" ADD CONSTRAINT "TCK_TICKETS_PK" PRIMARY KEY ("TCK_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."TICKETS" MODIFY ("TCK_RES_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."TICKETS" MODIFY ("TCK_TOTAL_IMPOSTS" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."TICKETS" MODIFY ("TCK_TOTAL_LTICKETS" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."TICKETS" MODIFY ("TCK_DATA_TICKET" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."TICKETS" MODIFY ("TCK_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OPINIONS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."OPINIONS" ADD CONSTRAINT "CK_OPI" CHECK (opi_opinio_revisada IN ('S','N')) ENABLE;
  ALTER TABLE "GESTIO"."OPINIONS" ADD CONSTRAINT "OPI_OPINIONS_PK" PRIMARY KEY ("OPI_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."OPINIONS" MODIFY ("OPI_USU_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."OPINIONS" MODIFY ("OPI_RES_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."OPINIONS" MODIFY ("OPI_OPINIO_REVISADA" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."OPINIONS" MODIFY ("OPI_PUNTUACIO" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."OPINIONS" MODIFY ("OPI_OBSERVACIO" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."OPINIONS" MODIFY ("OPI_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LTICKETS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."LTICKETS" ADD CONSTRAINT "LTK_LTICKETS_PK" PRIMARY KEY ("LTK_TCK_CODI", "LTK_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."LTICKETS" MODIFY ("LTK_TOTAL_UNITARI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."LTICKETS" MODIFY ("LTK_UNITATS" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."LTICKETS" MODIFY ("LTK_DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."LTICKETS" MODIFY ("LTK_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."LTICKETS" MODIFY ("LTK_TCK_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOG_INVOICES
--------------------------------------------------------

  ALTER TABLE "GESTIO"."LOG_INVOICES" ADD CONSTRAINT "LOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURES
--------------------------------------------------------

  ALTER TABLE "GESTIO"."FACTURES" ADD CONSTRAINT "CK_FAC" CHECK (fac_impresa IN ('S','N')) ENABLE;
  ALTER TABLE "GESTIO"."FACTURES" MODIFY ("FAC_IMPRESA" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."FACTURES" ADD CONSTRAINT "FAC_FACTURES_PK" PRIMARY KEY ("FAC_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."FACTURES" MODIFY ("FAC_RES_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."FACTURES" MODIFY ("FAC_TOTAL_A_PAGAR" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."FACTURES" MODIFY ("FAC_DATA_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."FACTURES" MODIFY ("FAC_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMATGES
--------------------------------------------------------

  ALTER TABLE "GESTIO"."IMATGES" ADD CONSTRAINT "IMG_IMATGES_PK" PRIMARY KEY ("IMG_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."IMATGES" MODIFY ("IMG_RES_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."IMATGES" MODIFY ("IMG_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMPOSTS
--------------------------------------------------------

  ALTER TABLE "GESTIO"."IMPOSTS" ADD CONSTRAINT "IMP_IMPOSTS_PK" PRIMARY KEY ("IMP_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."IMPOSTS" MODIFY ("IMP_PERCENTATGE" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."IMPOSTS" MODIFY ("IMP_DESCRIPCIO" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."IMPOSTS" MODIFY ("IMP_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMPXLTCK
--------------------------------------------------------

  ALTER TABLE "GESTIO"."IMPXLTCK" ADD CONSTRAINT "ILT_IMP_LTK_PK" PRIMARY KEY ("ILT_TCK_CODI", "ILT_LTK_CODI", "ILT_IMP_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GESTIO"."IMPXLTCK" MODIFY ("ILT_BASE" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."IMPXLTCK" MODIFY ("ILT_IMP_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."IMPXLTCK" MODIFY ("ILT_LTK_CODI" NOT NULL ENABLE);
  ALTER TABLE "GESTIO"."IMPXLTCK" MODIFY ("ILT_TCK_CODI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICES
--------------------------------------------------------

  ALTER TABLE "GESTIO"."INVOICES" ADD CONSTRAINT "INV_PK" PRIMARY KEY ("INV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LINVOICES
--------------------------------------------------------

  ALTER TABLE "GESTIO"."LINVOICES" ADD CONSTRAINT "LIN_PK" PRIMARY KEY ("LIN_INV_ID", "LIN_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
